# CMake generated Testfile for 
# Source directory: /home/riddle/gott/src/github.com/nats-io/cnats/test
# Build directory: /home/riddle/gott/src/github.com/nats-io/cnats/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Test_Version "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "0" "0")
set_tests_properties(Test_Version PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsNowAndSleep "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "1" "1")
set_tests_properties(Test_natsNowAndSleep PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsAllocSprintf "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "2" "2")
set_tests_properties(Test_natsAllocSprintf PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsStrCaseStr "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "3" "3")
set_tests_properties(Test_natsStrCaseStr PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsBuffer "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "4" "4")
set_tests_properties(Test_natsBuffer PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsParseInt64 "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "5" "5")
set_tests_properties(Test_natsParseInt64 PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsParseControl "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "6" "6")
set_tests_properties(Test_natsParseControl PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsNormalizeErr "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "7" "7")
set_tests_properties(Test_natsNormalizeErr PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsMutex "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "8" "8")
set_tests_properties(Test_natsMutex PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsThread "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "9" "9")
set_tests_properties(Test_natsThread PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsCondition "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "10" "10")
set_tests_properties(Test_natsCondition PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsTimer "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "11" "11")
set_tests_properties(Test_natsTimer PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsUrl "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "12" "12")
set_tests_properties(Test_natsUrl PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsCreateStringFromBuffer "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "13" "13")
set_tests_properties(Test_natsCreateStringFromBuffer PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsHash "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "14" "14")
set_tests_properties(Test_natsHash PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsHashing "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "15" "15")
set_tests_properties(Test_natsHashing PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsStrHash "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "16" "16")
set_tests_properties(Test_natsStrHash PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsInbox "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "17" "17")
set_tests_properties(Test_natsInbox PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsOptions "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "18" "18")
set_tests_properties(Test_natsOptions PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsSock_ConnectTcp "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "19" "19")
set_tests_properties(Test_natsSock_ConnectTcp PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsSock_IPOrder "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "20" "20")
set_tests_properties(Test_natsSock_IPOrder PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsSock_ReadLine "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "21" "21")
set_tests_properties(Test_natsSock_ReadLine PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsJSON "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "22" "22")
set_tests_properties(Test_natsJSON PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsErrWithLongText "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "23" "23")
set_tests_properties(Test_natsErrWithLongText PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_natsErrStackMoreThanMaxFrames "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "24" "24")
set_tests_properties(Test_natsErrStackMoreThanMaxFrames PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ReconnectServerStats "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "25" "25")
set_tests_properties(Test_ReconnectServerStats PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ParseStateReconnectFunctionality "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "26" "26")
set_tests_properties(Test_ParseStateReconnectFunctionality PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ServersRandomize "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "27" "27")
set_tests_properties(Test_ServersRandomize PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SelectNextServer "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "28" "28")
set_tests_properties(Test_SelectNextServer PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ParserPing "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "29" "29")
set_tests_properties(Test_ParserPing PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ParserErr "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "30" "30")
set_tests_properties(Test_ParserErr PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ParserOK "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "31" "31")
set_tests_properties(Test_ParserOK PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ParserSouldFail "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "32" "32")
set_tests_properties(Test_ParserSouldFail PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ParserSplitMsg "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "33" "33")
set_tests_properties(Test_ParserSplitMsg PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_LibMsgDelivery "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "34" "34")
set_tests_properties(Test_LibMsgDelivery PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_AsyncINFO "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "35" "35")
set_tests_properties(Test_AsyncINFO PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_RequestPool "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "36" "36")
set_tests_properties(Test_RequestPool PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_DefaultConnection "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "37" "37")
set_tests_properties(Test_DefaultConnection PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_IPResolutionOrder "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "38" "38")
set_tests_properties(Test_IPResolutionOrder PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_UseDefaultURLIfNoServerSpecified "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "39" "39")
set_tests_properties(Test_UseDefaultURLIfNoServerSpecified PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ConnectToWithMultipleURLs "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "40" "40")
set_tests_properties(Test_ConnectToWithMultipleURLs PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ConnectionWithNULLOptions "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "41" "41")
set_tests_properties(Test_ConnectionWithNULLOptions PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ConnectionStatus "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "42" "42")
set_tests_properties(Test_ConnectionStatus PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ConnClosedCB "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "43" "43")
set_tests_properties(Test_ConnClosedCB PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_CloseDisconnectedCB "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "44" "44")
set_tests_properties(Test_CloseDisconnectedCB PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ServerStopDisconnectedCB "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "45" "45")
set_tests_properties(Test_ServerStopDisconnectedCB PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ClosedConnections "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "46" "46")
set_tests_properties(Test_ClosedConnections PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ConnectVerboseOption "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "47" "47")
set_tests_properties(Test_ConnectVerboseOption PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ReconnectTotalTime "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "48" "48")
set_tests_properties(Test_ReconnectTotalTime PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ReconnectDisallowedFlags "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "49" "49")
set_tests_properties(Test_ReconnectDisallowedFlags PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ReconnectAllowedFlags "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "50" "50")
set_tests_properties(Test_ReconnectAllowedFlags PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ConnCloseBreaksReconnectLoop "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "51" "51")
set_tests_properties(Test_ConnCloseBreaksReconnectLoop PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_BasicReconnectFunctionality "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "52" "52")
set_tests_properties(Test_BasicReconnectFunctionality PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ExtendedReconnectFunctionality "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "53" "53")
set_tests_properties(Test_ExtendedReconnectFunctionality PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_QueueSubsOnReconnect "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "54" "54")
set_tests_properties(Test_QueueSubsOnReconnect PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_IsClosed "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "55" "55")
set_tests_properties(Test_IsClosed PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_IsReconnectingAndStatus "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "56" "56")
set_tests_properties(Test_IsReconnectingAndStatus PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ReconnectBufSize "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "57" "57")
set_tests_properties(Test_ReconnectBufSize PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ErrOnConnectAndDeadlock "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "58" "58")
set_tests_properties(Test_ErrOnConnectAndDeadlock PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ErrOnMaxPayloadLimit "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "59" "59")
set_tests_properties(Test_ErrOnMaxPayloadLimit PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_Auth "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "60" "60")
set_tests_properties(Test_Auth PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_AuthFailNoDisconnectCB "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "61" "61")
set_tests_properties(Test_AuthFailNoDisconnectCB PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_AuthToken "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "62" "62")
set_tests_properties(Test_AuthToken PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_PermViolation "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "63" "63")
set_tests_properties(Test_PermViolation PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_AuthViolation "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "64" "64")
set_tests_properties(Test_AuthViolation PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ConnectedServer "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "65" "65")
set_tests_properties(Test_ConnectedServer PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_MultipleClose "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "66" "66")
set_tests_properties(Test_MultipleClose PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SimplePublish "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "67" "67")
set_tests_properties(Test_SimplePublish PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SimplePublishNoData "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "68" "68")
set_tests_properties(Test_SimplePublishNoData PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_PublishMsg "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "69" "69")
set_tests_properties(Test_PublishMsg PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_InvalidSubsArgs "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "70" "70")
set_tests_properties(Test_InvalidSubsArgs PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_AsyncSubscribe "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "71" "71")
set_tests_properties(Test_AsyncSubscribe PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_AsyncSubscribeTimeout "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "72" "72")
set_tests_properties(Test_AsyncSubscribeTimeout PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SyncSubscribe "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "73" "73")
set_tests_properties(Test_SyncSubscribe PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_PubSubWithReply "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "74" "74")
set_tests_properties(Test_PubSubWithReply PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_Flush "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "75" "75")
set_tests_properties(Test_Flush PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_QueueSubscriber "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "76" "76")
set_tests_properties(Test_QueueSubscriber PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ReplyArg "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "77" "77")
set_tests_properties(Test_ReplyArg PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SyncReplyArg "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "78" "78")
set_tests_properties(Test_SyncReplyArg PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_Unsubscribe "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "79" "79")
set_tests_properties(Test_Unsubscribe PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_DoubleUnsubscribe "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "80" "80")
set_tests_properties(Test_DoubleUnsubscribe PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_RequestTimeout "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "81" "81")
set_tests_properties(Test_RequestTimeout PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_Request "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "82" "82")
set_tests_properties(Test_Request PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_RequestNoBody "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "83" "83")
set_tests_properties(Test_RequestNoBody PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_OldRequest "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "84" "84")
set_tests_properties(Test_OldRequest PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SimultaneousRequests "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "85" "85")
set_tests_properties(Test_SimultaneousRequests PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_RequestClose "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "86" "86")
set_tests_properties(Test_RequestClose PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_FlushInCb "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "87" "87")
set_tests_properties(Test_FlushInCb PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ReleaseFlush "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "88" "88")
set_tests_properties(Test_ReleaseFlush PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_FlushErrOnDisconnect "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "89" "89")
set_tests_properties(Test_FlushErrOnDisconnect PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_Inbox "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "90" "90")
set_tests_properties(Test_Inbox PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_Stats "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "91" "91")
set_tests_properties(Test_Stats PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_BadSubject "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "92" "92")
set_tests_properties(Test_BadSubject PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ClientAsyncAutoUnsub "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "93" "93")
set_tests_properties(Test_ClientAsyncAutoUnsub PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ClientSyncAutoUnsub "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "94" "94")
set_tests_properties(Test_ClientSyncAutoUnsub PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ClientAutoUnsubAndReconnect "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "95" "95")
set_tests_properties(Test_ClientAutoUnsubAndReconnect PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_NextMsgOnClosedSub "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "96" "96")
set_tests_properties(Test_NextMsgOnClosedSub PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_CloseSubRelease "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "97" "97")
set_tests_properties(Test_CloseSubRelease PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_IsValidSubscriber "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "98" "98")
set_tests_properties(Test_IsValidSubscriber PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SlowSubscriber "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "99" "99")
set_tests_properties(Test_SlowSubscriber PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SlowAsyncSubscriber "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "100" "100")
set_tests_properties(Test_SlowAsyncSubscriber PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_PendingLimitsDeliveredAndDropped "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "101" "101")
set_tests_properties(Test_PendingLimitsDeliveredAndDropped PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_PendingLimitsWithSyncSub "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "102" "102")
set_tests_properties(Test_PendingLimitsWithSyncSub PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_AsyncSubscriptionPending "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "103" "103")
set_tests_properties(Test_AsyncSubscriptionPending PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_AsyncSubscriptionPendingDrain "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "104" "104")
set_tests_properties(Test_AsyncSubscriptionPendingDrain PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SyncSubscriptionPending "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "105" "105")
set_tests_properties(Test_SyncSubscriptionPending PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SyncSubscriptionPendingDrain "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "106" "106")
set_tests_properties(Test_SyncSubscriptionPendingDrain PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_AsyncErrHandler "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "107" "107")
set_tests_properties(Test_AsyncErrHandler PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_AsyncSubscriberStarvation "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "108" "108")
set_tests_properties(Test_AsyncSubscriberStarvation PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_AsyncSubscriberOnClose "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "109" "109")
set_tests_properties(Test_AsyncSubscriberOnClose PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_NextMsgCallOnAsyncSub "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "110" "110")
set_tests_properties(Test_NextMsgCallOnAsyncSub PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_GetLastError "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "111" "111")
set_tests_properties(Test_GetLastError PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_StaleConnection "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "112" "112")
set_tests_properties(Test_StaleConnection PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ServerErrorClosesConnection "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "113" "113")
set_tests_properties(Test_ServerErrorClosesConnection PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SSLBasic "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "114" "114")
set_tests_properties(Test_SSLBasic PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SSLVerify "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "115" "115")
set_tests_properties(Test_SSLVerify PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SSLVerifyHostname "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "116" "116")
set_tests_properties(Test_SSLVerifyHostname PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SSLSkipServerVerification "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "117" "117")
set_tests_properties(Test_SSLSkipServerVerification PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SSLCiphers "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "118" "118")
set_tests_properties(Test_SSLCiphers PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SSLMultithreads "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "119" "119")
set_tests_properties(Test_SSLMultithreads PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_SSLConnectVerboseOption "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "120" "120")
set_tests_properties(Test_SSLConnectVerboseOption PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ServersOption "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "121" "121")
set_tests_properties(Test_ServersOption PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_AuthServers "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "122" "122")
set_tests_properties(Test_AuthServers PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_AuthFailToReconnect "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "123" "123")
set_tests_properties(Test_AuthFailToReconnect PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_BasicClusterReconnect "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "124" "124")
set_tests_properties(Test_BasicClusterReconnect PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_HotSpotReconnect "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "125" "125")
set_tests_properties(Test_HotSpotReconnect PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ProperReconnectDelay "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "126" "126")
set_tests_properties(Test_ProperReconnectDelay PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ProperFalloutAfterMaxAttempts "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "127" "127")
set_tests_properties(Test_ProperFalloutAfterMaxAttempts PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_ProperFalloutMaxAttemptsAuth "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "128" "128")
set_tests_properties(Test_ProperFalloutMaxAttemptsAuth PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_TimeoutOnNoServer "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "129" "129")
set_tests_properties(Test_TimeoutOnNoServer PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_PingReconnect "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "130" "130")
set_tests_properties(Test_PingReconnect PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_GetServers "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "131" "131")
set_tests_properties(Test_GetServers PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_GetDiscoveredServers "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "132" "132")
set_tests_properties(Test_GetDiscoveredServers PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
add_test(Test_DiscoveredServersCb "/home/riddle/gott/src/github.com/nats-io/cnats/test/testsuite" "133" "133")
set_tests_properties(Test_DiscoveredServersCb PROPERTIES  PASS_REGULAR_EXPRESSION "ALL PASSED" WORKING_DIRECTORY "/home/riddle/gott/src/github.com/nats-io/cnats/test")
